import type { PolicyConfig } from './schema';

export const DEFAULT_CONFIG_PATH = '.github/policy-gate.yml';

export function createDefaultPolicyConfig(): PolicyConfig {
  return {
    policies: [
      {
        id: 'workflow-change-needs-runbook',
        description:
          'Workflow changes should include runbook or rollback context.',
        severity: 'warn',
        when: {
          changed: ['.github/workflows/**'],
        },
        require: {
          any: [
            { changed: ['docs/runbooks/**'] },
            { pr_text: ['runbook', 'rollback'] },
          ],
        },
        message:
          'Workflow changes should include runbook or rollback evidence before merge.',
      },
      {
        id: 'api-change-needs-release-note',
        description:
          'Public API changes should include changelog or a release-note label.',
        severity: 'warn',
        when: {
          changed: ['api/public/**'],
        },
        require: {
          any: [
            { changed: ['CHANGELOG.md'] },
            { has_label: ['release-note-exempt'] },
          ],
        },
        message:
          'Public API changes should include a changelog update or release-note label.',
      },
    ],
  };
}

export function renderDefaultPolicyConfig(): string {
  return [
    '# Generated by github-policy-gate because no config file was found.',
    '# This temporary fallback is advisory only and does not fail the job.',
    'policies:',
    '  - id: workflow-change-needs-runbook',
    '    description: Workflow changes should include runbook or rollback context.',
    '    severity: warn',
    '    when:',
    '      changed:',
    '        - ".github/workflows/**"',
    '    require:',
    '      any:',
    '        - changed:',
    '            - "docs/runbooks/**"',
    '        - pr_text:',
    '            - "runbook"',
    '            - "rollback"',
    '    message: Workflow changes should include runbook or rollback evidence before merge.',
    '  - id: api-change-needs-release-note',
    '    description: Public API changes should include changelog or a release-note label.',
    '    severity: warn',
    '    when:',
    '      changed:',
    '        - "api/public/**"',
    '    require:',
    '      any:',
    '        - changed:',
    '            - "CHANGELOG.md"',
    '        - has_label:',
    '            - "release-note-exempt"',
    '    message: Public API changes should include a changelog update or release-note label.',
    '',
  ].join('\n');
}
